name: build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-image:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # chmod
      - name: set execute permission
        run: sudo chmod +x ./Source/Tools/icnspack
      
      - name: Run build script
        run: sudo sudo python3 ./buildicns.py

      - name: Zip icns folder
        run: cd ./Export && zip -r icns.zip ./icns

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: icns
          path: ./Export/icns.zip
